#!/usr/bin/env sh
alias ka="killall" \
	mkd="mkdir -pv" \
	mpv="mpv --input-ipc-server=/tmp/mpvsoc$(date +%s)" \
	calcurse="calcurse -D ~/.config/calcurse" \
	magit="nvim -c MagitOnly" \
	p="sudo pacman" \
	SS="sudo systemctl" \
	f="$FILE" \
	g="git" \
	trem="transmission-remote" \
	e="$EDITOR" \
	v="$EDITOR" \
	x="sxiv -ft *" \
	sdn="sudo shutdown -h now" \
	gua="git remote | xargs -L1 git push --all" \
	ls="ls -hNA --color=auto --group-directories-first" \
	grep="grep --color=auto" \
	diff="diff --color=auto" \
	ccat="highlight --out-format=ansi" \
	yt="youtube-dl --add-metadata -i -o '%(upload_date)s-%(title)s.%(ext)s'" \
	yta="yt -x -f bestaudio/best" \
	YT="youtube-viewer" \
	ref="shortcuts >/dev/null; source ~/.config/shortcutrc" \
	upc="sudo pacman -Syu; pkill -RTMIN+8 i3blocks" \
	lsp="pacman -Qett --color=always | less" \
	ffmpeg="ffmpeg -hide_banner"

# My custom Functions and my own alias list

function taskProject(){
	echo "Please enter a task number \n followed by a project name."
	task $1 modify project:$2
}

function taskTag(){
	task $1 modify +$2
}

alias ls=lsd \
	ll="ls -l -A" \
	ta="task add $1" \
	report="task burndown.daily" \
	t="task list" \
	h="cd $HOME && taskell"
	tpro=taskproject \
	tt=taskTag \
	scim=sc-im \
	tellico=$HOME/.local/bin/tools/tellico \
	jn="jupyter notebook" \
	bib="vim $HOME/Documents/bib/uni.bib"

# end my custom alias's and functions

command -v nvim >/dev/null && alias vim="nvim" vimdiff="nvim -d" # Use neovim for vim if present.

vf() { fzf | xargs -r -I % $EDITOR % ;}


